# Generated by Django 3.1.3 on 2020-11-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginandregistation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_information',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
