# Generated by Django 3.1.3 on 2020-11-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type_name', models.CharField(max_length=255, unique=True)),
                ('structure', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type_id', models.IntegerField()),
                ('token_type_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TokenProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField()),
                ('step', models.IntegerField()),
                ('to', models.CharField(max_length=255)),
                ('state_of_emergency', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('token_id', 'step')},
            },
        ),
        migrations.CreateModel(
            name='TokenBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField()),
                ('step', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
                ('approval', models.BooleanField(default=False)),
                ('state_of_emergency', models.BooleanField(default=False)),
                ('body', models.JSONField()),
            ],
            options={
                'unique_together': {('token_id', 'step')},
            },
        ),
    ]
