# Generated by Django 3.1.3 on 2020-11-20 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenbody',
            name='completed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tokenprogress',
            name='completed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
