# Generated by Django 3.1.3 on 2020-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmins', '0004_auto_20201212_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendefinition',
            name='can_create',
            field=models.JSONField(default='{"can_create": ["students"]}', max_length=255),
        ),
    ]
