# Generated by Django 3.1.3 on 2020-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmins', '0005_auto_20201212_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokendefinition',
            name='can_create',
            field=models.JSONField(default='{"can_create": ["students"]}'),
        ),
    ]
