# Generated by Django 3.1.3 on 2020-12-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmins', '0007_auto_20201212_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokendefinition',
            name='can_create',
        ),
    ]
