# Generated by Django 3.1.3 on 2020-12-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemadmins', '0008_remove_tokendefinition_can_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokendefinition',
            name='can_create',
            field=models.CharField(default='students', max_length=255),
        ),
    ]
